kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
## This is intentionally left as one node for since bpf programs are not namespaced
## which can lead to confusing scenarios when listing all bpf programs.
- role: control-plane
