[package]
name = "bpfd-api"
version = "0.1.0"
edition = "2021"
description = "gRPC bindings to the bpfd API"
license = "MIT OR Apache-2.0"
repository = "https://github.com/redhat-et/bpfd"

[dependencies]
tonic = { version = "0.8", features = ["tls"] }
prost = "0.11"
thiserror = "1"
tokio = { version = "1.21.2", features = ["full"] }
log = "0.4"
nix = { version = "0.25", features = [ "socket", "fs", "mount"]}
openssl = { version = "0.10.41", features = ["vendored"] }
