---
extends: default
rules:
  line-length: disable
  document-start: disable
  comments:
    min-spaces-from-content: 1
ignore:
  - libbpf/*
  - bpfd-operator/config/crd/*
  - bpfd-operator/config/rbac/*
