# These SCC OCP workarounds are left here for possible future reference even
# though they are not currently in use.
# apiVersion: v1
# kind: Namespace
# metadata:
#   labels:
#     openshift.io/cluster-monitoring: "true"
#     pod-security.kubernetes.io/enforce: privileged
#     pod-security.kubernetes.io/audit: privileged
#     pod-security.kubernetes.io/warn: privileged
#   annotations:
#     openshift.io/node-selector: ""
#     openshift.io/description: "Openshift bpfman components"
#     workload.openshift.io/allowed: "management"
#   name: openshift-bpfman
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: privileged-scc
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: system:openshift:scc:privileged
# subjects:
# - kind: ServiceAccount
#   name: bpfman-daemon
#   namespace: openshift-bpfman
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bpfman-agent-cert
  namespace: openshift-bpfman
spec:
  commonName: bpfman-agent
  dnsNames:
    - localhost
  ipAddresses:
    - 127.0.0.1
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: bpfman-cert-issuer
  privateKey:
    algorithm: RSA
  secretName: bpfman-agent-cert-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bpfman-ca
  namespace: openshift-bpfman
spec:
  commonName: bpfman-ca
  isCA: true
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: bpfman-cert-cluster-issuer
  privateKey:
    algorithm: RSA
  secretName: bpfman-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bpfman-cert
  namespace: openshift-bpfman
spec:
  commonName: bpfman
  dnsNames:
    - localhost
  ipAddresses:
    - 127.0.0.1
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: bpfman-cert-issuer
  privateKey:
    algorithm: RSA
  secretName: bpfman-cert-secret
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: bpfman-cert-cluster-issuer
  namespace: openshift-bpfman
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: bpfman-cert-issuer
  namespace: openshift-bpfman
spec:
  ca:
    secretName: bpfman-ca
