resources:
  ## If changing the version of cert-manager version update CERTMANAGER_VERSION in .github/workflows/test.yml
  - https://github.com/cert-manager/cert-manager/releases/download/v1.10.1/cert-manager.yaml
