apiVersion: v1
data:
  bpfman.agent.image: quay.io/bpfman/bpfman-agent:latest
  bpfman.agent.log.level: info
  bpfman.image: quay.io/bpfman/bpfman:latest
  bpfman.log.level: info
kind: ConfigMap
metadata:
  name: bpfman-config
