apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: bpfd-operator
    app.kubernetes.io/instance: system
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: namespace
    app.kubernetes.io/part-of: bpfd-operator
    control-plane: controller-manager
  name: bpfd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bpfd-daemon
  namespace: bpfd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bpfd-operator
  namespace: bpfd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bpfd-operator
    app.kubernetes.io/instance: leader-election-role
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: role
    app.kubernetes.io/part-of: bpfd-operator
  name: bpfd-leader-election-role
  namespace: bpfd
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: bpfd-agent-role
rules:
- apiGroups:
  - bpfd.io
  resources:
  - bpfprograms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfd.io
  resources:
  - bpfprograms/finalizers
  verbs:
  - update
- apiGroups:
  - bpfd.io
  resources:
  - bpfprograms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bpfd.io
  resources:
  - tcprograms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bpfd.io
  resources:
  - tcprograms/finalizers
  verbs:
  - update
- apiGroups:
  - bpfd.io
  resources:
  - tracepointprograms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bpfd.io
  resources:
  - tracepointprograms/finalizers
  verbs:
  - update
- apiGroups:
  - bpfd.io
  resources:
  - xdpprograms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bpfd.io
  resources:
  - xdpprograms/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bpfd-operator
    app.kubernetes.io/instance: bpfprogram-editor-role
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/part-of: bpfd-operator
  name: bpfd-bpfprogram-editor-role
rules:
- apiGroups:
  - bpfd.io
  resources:
  - bpfprograms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfd.io
  resources:
  - bpfprograms/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bpfd-operator
    app.kubernetes.io/instance: bpfprogram-viewer-role
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/part-of: bpfd-operator
  name: bpfd-bpfprogram-viewer-role
rules:
- apiGroups:
  - bpfd.io
  resources:
  - bpfprograms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bpfd.io
  resources:
  - bpfprograms/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: bpfd-operator
    app.kubernetes.io/instance: metrics-reader
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/part-of: bpfd-operator
  name: bpfd-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: bpfd-operator-role
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfd.io
  resources:
  - bpfprograms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bpfd.io
  resources:
  - configmaps/finalizers
  verbs:
  - update
- apiGroups:
  - bpfd.io
  resources:
  - tcprograms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfd.io
  resources:
  - tcprograms/finalizers
  verbs:
  - update
- apiGroups:
  - bpfd.io
  resources:
  - tcprograms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bpfd.io
  resources:
  - tracepointprograms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfd.io
  resources:
  - tracepointprograms/finalizers
  verbs:
  - update
- apiGroups:
  - bpfd.io
  resources:
  - tracepointprograms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bpfd.io
  resources:
  - xdpprograms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfd.io
  resources:
  - xdpprograms/finalizers
  verbs:
  - update
- apiGroups:
  - bpfd.io
  resources:
  - xdpprograms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: bpfd-operator
    app.kubernetes.io/instance: proxy-role
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/part-of: bpfd-operator
  name: bpfd-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bpfd-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/part-of: bpfd-operator
  name: bpfd-agent-rolebinding
  namespace: bpfd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bpfd-agent-role
subjects:
- kind: ServiceAccount
  name: bpfd-daemon
  namespace: bpfd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bpfd-operator
    app.kubernetes.io/instance: leader-election-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/part-of: bpfd-operator
  name: bpfd-leader-election-rolebinding
  namespace: bpfd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bpfd-leader-election-role
subjects:
- kind: ServiceAccount
  name: bpfd-operator
  namespace: bpfd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bpfd-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/part-of: bpfd-operator
  name: bpfd-agent-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bpfd-agent-role
subjects:
- kind: ServiceAccount
  name: bpfd-daemon
  namespace: bpfd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bpfd-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/part-of: bpfd-operator
  name: bpfd-bpfd-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bpfd-operator-role
subjects:
- kind: ServiceAccount
  name: bpfd-operator
  namespace: bpfd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: bpfd-operator
    app.kubernetes.io/instance: proxy-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/part-of: bpfd-operator
  name: bpfd-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bpfd-proxy-role
subjects:
- kind: ServiceAccount
  name: bpfd-operator
  namespace: bpfd
---
apiVersion: v1
data:
  bpfd.agent.image: quay.io/bpfd/bpfd-agent:v0.2.0
  bpfd.image: quay.io/bpfd/bpfd:v0.2.0
  bpfd.log.level: debug
  bpfd.toml: |
    [tls] # REQUIRED
    ca_cert = "/etc/bpfd/certs/ca/ca.crt"
    cert = "/etc/bpfd/certs/bpfd/tls.crt"
    key = "/etc/bpfd/certs/bpfd/tls.key"
    client_cert = "/etc/bpfd/certs/bpfd-client/tls.crt"
    client_key = "/etc/bpfd/certs/bpfd-client/tls.key"
kind: ConfigMap
metadata:
  name: bpfd-config
  namespace: bpfd
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: bpfd-operator
    app.kubernetes.io/instance: controller-manager-metrics-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: bpfd-operator
    control-plane: controller-manager
  name: bpfd-controller-manager-metrics-service
  namespace: bpfd
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: bpfd-operator
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: deployment
    app.kubernetes.io/part-of: bpfd-operator
    control-plane: controller-manager
  name: bpfd-operator
  namespace: bpfd
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
                - ppc64le
                - s390x
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=0
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 5m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        command:
        - /bpfd-operator
        env:
        - name: GO_LOG
          value: info
        image: quay.io/bpfd/bpfd-operator:v0.2.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: bpfd-operator
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
      serviceAccountName: bpfd-operator
      terminationGracePeriodSeconds: 10
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bpfd-agent-cert
  namespace: bpfd
spec:
  commonName: bpfd-agent
  dnsNames:
  - localhost
  ipAddresses:
  - 127.0.0.1
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: bpfd-cert-issuer
  privateKey:
    algorithm: RSA
  secretName: bpfd-agent-cert-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bpfd-ca
  namespace: bpfd
spec:
  commonName: bpfd-ca
  isCA: true
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: bpfd-cert-cluster-issuer
  privateKey:
    algorithm: RSA
  secretName: bpfd-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bpfd-cert
  namespace: bpfd
spec:
  commonName: bpfd
  dnsNames:
  - localhost
  ipAddresses:
  - 127.0.0.1
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: bpfd-cert-issuer
  privateKey:
    algorithm: RSA
  secretName: bpfd-cert-secret
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: bpfd-cert-cluster-issuer
  namespace: bpfd
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: bpfd-cert-issuer
  namespace: bpfd
spec:
  ca:
    secretName: bpfd-ca
