resources:
- config.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: quay.io/bpfman/bpfman
  newName: quay.io/bpfman/bpfman
  newTag: latest
- name: quay.io/bpfman/bpfman-agent
  newName: quay.io/bpfman/bpfman-agent
  newTag: latest
