---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert # name of this object
spec:
  dnsNames:
    - localhost
  ipAddresses:
    - 127.0.0.1
  commonName: bpfd
  secretName: bpfd-cert-secret
  privateKey:
    algorithm: RSA
  issuerRef:
    name: bpfd-cert-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: agent-cert # name of this object
spec:
  dnsNames:
    - localhost
  ipAddresses:
    - 127.0.0.1
  commonName: bpfd-agent
  secretName: bpfd-agent-cert-secret
  privateKey:
    algorithm: RSA
  issuerRef:
    name: bpfd-cert-issuer
    kind: Issuer
    group: cert-manager.io
