---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-cluster-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca
spec:
  isCA: true
  commonName: bpfd-ca
  secretName: bpfd-ca
  privateKey:
    algorithm: RSA
  issuerRef:
    name: bpfd-cert-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cert-issuer
spec:
  ca:
    secretName: bpfd-ca
