# CRD can be used with the nginx-deployment.yaml in this directory
apiVersion: bpfman.io/v1alpha1
kind: UprobeProgram
metadata:
  labels:
    app.kubernetes.io/name: uprobeprogram
  name: uprobe-example-nginx
spec:
  # Select all nodes
  nodeselector: {}
  bpffunctionname: my_uprobe
  func_name: malloc
  # offset: 0 # optional offset w/in function
  target: libc
  retprobe: false
  # pid: 0 # optional pid to execute uprobe for
  bytecode:
    image:
      url: quay.io/bpfman-bytecode/uprobe:latest
  globaldata:
    GLOBAL_u8:
      - 0x01
    GLOBAL_u32:
      - 0x0D
      - 0x0C
      - 0x0B
      - 0x0A
  containers:
    namespace: default
    pods:
      matchLabels: {}
    containernames:
      - nginx
