apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: kube-system
data:
  ## Can be configured at runtime
  bpfd.agent.image: quay.io/bpfd/bpfd-agent:latest
  bpfd.image: quay.io/bpfd/bpfd:latest
  ## Can be set to "info", "debug", or "trace"
  bpfd.agent.log.level: "info"
  ## See https://docs.rs/env_logger/latest/env_logger/ for configuration options
  bpfd.log.level: "info"
  ## Must be configured at startup
  bpfd.toml: |
    [[grpc.endpoints]]
    type = "unix"
    path = "/bpfd-sock/bpfd.sock"
    enabled = true
