## This is part of the payload deployed by the bpfd-operator NOT kustomize.
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi.bpfd.dev
spec:
  attachRequired: false
  podInfoOnMount: true
  volumeLifecycleModes:
  - Ephemeral
