## This is part of the payload deployed by the bpfd-operator NOT kustomize.
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi.bpfd.dev
  labels:
    security.openshift.io/csi-ephemeral-volume-profile: baseline
spec:
  attachRequired: true
  podInfoOnMount: true
  fsGroupPolicy: File
  volumeLifecycleModes:
    - Ephemeral
