resources:
- config.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: quay.io/bpfd/bpfd
  newName: quay.io/bpfd/bpfd
  newTag: v0.3.0
- name: quay.io/bpfd/bpfd-agent
  newName: quay.io/bpfd/bpfd-agent
  newTag: v0.3.0
